# Generated by Django 3.2.8 on 2021-11-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('tipo_producto', models.PositiveSmallIntegerField(choices=[(0, 'Receta'), (1, 'Truco')])),
                ('path_video', models.CharField(max_length=800)),
                ('precio_pts', models.IntegerField()),
            ],
        ),
    ]
