# Generated by Django 3.2.8 on 2021-11-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='file',
            field=models.FileField(db_column='image_url', null=True, upload_to='images/productos'),
        ),
    ]
