# Generated by Django 3.2.8 on 2021-11-13 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pregunta', models.CharField(max_length=800)),
                ('puntos', models.IntegerField(default=50)),
                ('tipo_actividad', models.PositiveSmallIntegerField(choices=[(0, 'Trivia'), (1, 'Completado de columnas'), (2, 'Relacionamiento de imagenes')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('path_video', models.CharField(max_length=800)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opcion', models.CharField(max_length=800)),
                ('op_correcta', models.BooleanField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcion_actividad', to='activities.actividad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
