# Generated by Django 3.2.8 on 2021-10-13 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pregunta', models.CharField(max_length=500, null=True)),
                ('tipo_actividad', models.PositiveSmallIntegerField(choices=[(0, 'Trivia'), (1, 'Completado de columnas'), (2, 'Relacionamiento de imagenes')], default=1)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_nivel', to='levels.nivel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opcion', models.CharField(max_length=500, null=True)),
                ('op_correcta', models.CharField(max_length=500, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcion_actividad', to='activities.actividad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
