# Generated by Django 3.2.8 on 2021-11-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='puntos',
            field=models.IntegerField(default=50),
        ),
    ]
