# Generated by Django 3.2.8 on 2021-11-13 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leccion_nivel', to='levels.nivel'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_leccion', to='activities.leccion'),
        ),
    ]
