# Generated by Django 3.2.8 on 2021-11-13 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_remove_nivel_rutina'),
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rutina',
            name='nivel',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rutina_nivel', to='levels.nivel'),
            preserve_default=False,
        ),
    ]
