# Generated by Django 3.2.8 on 2021-11-13 23:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0002_auto_20211113_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
