# Generated by Django 3.2.8 on 2021-11-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyinfo',
            name='altura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bodyinfo',
            name='body_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ectomorfo'), (1, 'Endomorfo'), (2, 'Mesomorfo')]),
        ),
        migrations.AlterField(
            model_name='bodyinfo',
            name='calorias',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bodyinfo',
            name='objetivo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Hipertrofia'), (1, 'Definición'), (2, 'Resistencia')]),
        ),
        migrations.AlterField(
            model_name='bodyinfo',
            name='peso',
            field=models.IntegerField(),
        ),
    ]
