# Generated by Django 3.2.8 on 2021-11-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='producto',
            field=models.ManyToManyField(blank=True, to='store.Producto'),
        ),
    ]
