# Generated by Django 3.2.8 on 2021-11-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyinfo',
            name='calorias',
            field=models.FloatField(),
        ),
    ]
