# Generated by Django 3.2.8 on 2021-11-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
        ('authentication', '0004_alter_bodyinfo_calorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_nivel', to='levels.nivel'),
        ),
    ]
