# Generated by Django 3.2.8 on 2021-11-13 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='rutina',
        ),
    ]
